sudo: false
language: node_js

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "8"
      env: NO_WATCH_TESTS=1 JOB_PART=lint
    # - os: linux
    #   node_js: "8"
    #   env: NO_WATCH_TESTS=1 JOB_PART=unit
    # - os: windows
    #   node_js: "8"
    #   env: NO_WATCH_TESTS=1 JOB_PART=unit
    # - os: osx
    #   node_js: "8"
    #   env: NO_WATCH_TESTS=1 JOB_PART=unit
  fast_finish: true

install:
  - yarn --frozen-lockfile
  - yarn link --frozen-lockfile || true
  - yarn link webpack --frozen-lockfile

script: npm run travis:$JOB_PART
