sudo: false
language: node_js

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "8"
      env: JOB_PART=lint
    - os: linux
      node_js: "8"
      env: JOB_PART=unit
    - os: windows
      node_js: "8"
      env: JOB_PART=unit
    - os: osx
      node_js: "8"
      env: JOB_PART=unit
  fast_finish: true

install:
  - yarn install

script: npm run travis:$JOB_PART

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage